/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * TDEngine Timestamp as Date
     */
    tdDate<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "TDDate";
    /**
     * TDEngine Timestamp
     */
    ts<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Timestamp";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * TDEngine Timestamp as Date
     */
    tdDate<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "TDDate";
    /**
     * TDEngine Timestamp
     */
    ts<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Timestamp";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  TDDate: any
  Timestamp: any
}

export interface NexusGenObjects {
  Query: {};
  Vessel: { // root type
    imo?: string | null; // String
    mmsi: string; // String!
    movement: NexusGenRootTypes['VesselMovement']; // VesselMovement!
    name: string; // String!
  }
  VesselMovement: { // root type
    heading: number; // Float!
    latitude: number; // Float!
    longitude: number; // Float!
    mmsi: string; // String!
    name: string; // String!
    nav_status: number; // Int!
    speed: number; // Float!
    ts: NexusGenScalars['Timestamp']; // Timestamp!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Query: { // field return type
    latestMovement: NexusGenRootTypes['Vessel']; // Vessel!
    latestMovements: NexusGenRootTypes['VesselMovement'][]; // [VesselMovement!]!
    vessels: NexusGenRootTypes['Vessel'][]; // [Vessel!]!
  }
  Vessel: { // field return type
    imo: string | null; // String
    mmsi: string; // String!
    movement: NexusGenRootTypes['VesselMovement']; // VesselMovement!
    name: string; // String!
  }
  VesselMovement: { // field return type
    heading: number; // Float!
    latitude: number; // Float!
    longitude: number; // Float!
    mmsi: string; // String!
    name: string; // String!
    nav_status: number; // Int!
    speed: number; // Float!
    ts: NexusGenScalars['Timestamp']; // Timestamp!
  }
}

export interface NexusGenFieldTypeNames {
  Query: { // field return type name
    latestMovement: 'Vessel'
    latestMovements: 'VesselMovement'
    vessels: 'Vessel'
  }
  Vessel: { // field return type name
    imo: 'String'
    mmsi: 'String'
    movement: 'VesselMovement'
    name: 'String'
  }
  VesselMovement: { // field return type name
    heading: 'Float'
    latitude: 'Float'
    longitude: 'Float'
    mmsi: 'String'
    name: 'String'
    nav_status: 'Int'
    speed: 'Float'
    ts: 'Timestamp'
  }
}

export interface NexusGenArgTypes {
  Query: {
    latestMovement: { // args
      mmsi?: string | null; // String
    }
    vessels: { // args
      mmsi?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: false
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}